# ═══════════════════════════════════════════════════════════════════════════════
# 硬件配置 —— 由 nixos-generate-config 自动生成
#
#   ⚠️ 重要提示：
#   此文件由 nixos-generate-config 工具根据本机硬件自动生成。
#   每次执行以下命令都会重新生成本文件，覆盖手动修改：
#
#     sudo nixos-generate-config --show-hardware-config \
#       > hosts/westwood/hardware-configuration.nix
#
#   此文件包含：
#   - 初始化内存盘（initrd）所需的内核模块（用于挂载根文件系统）
#   - 文件系统挂载点（/ 根分区、/boot EFI 分区等）及其 UUID
#   - 交换设备
#   - 平台架构和 Intel CPU 微码更新
#
#   ⚠️ 自动生成 → 不要手动编辑！
#   如需持久化的硬件配置（如内核参数、NVIDIA 驱动等），请放入 hardware.nix。
# ═══════════════════════════════════════════════════════════════════════════════

# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # 初始化内存盘内核模块 —— 用于在早期启动阶段识别存储设备
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # 根文件系统 —— ext4 格式，通过 UUID 标识
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66f9d82e-4f4b-4a13-a7d6-060fe92ad048";
      fsType = "ext4";
    };

  # EFI 系统分区 —— vfat 格式，存放引导加载器
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CA3E-5547";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # 无单独交换分区（交换空间由 zram + swapfile 在 hardware.nix 中管理）
  swapDevices = [ ];

  # 平台架构和 CPU 微码
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
